from pathlib import Path
root=Path('/mnt/data/phase5')
main=root/'src/main.tsx'; css=root/'src/styles.css'; html=root/'index.html'
t=main.read_text()
# Import React namespace for ErrorBoundary while preserving existing hooks import.
t=t.replace('import {useEffect,useRef,useState,type FormEvent} from "react";','import React,{useEffect,useRef,useState,type FormEvent} from "react";')
marker='function beep(){try{navigator.vibrate?.(75)}catch{}}\n'
extra='''\nfunction registerServiceWorker(){\n  if("serviceWorker" in navigator){\n    window.addEventListener("load",()=>{navigator.serviceWorker.register("/sw.js").catch(()=>{})});\n  }\n}\n\nclass AppErrorBoundary extends React.Component<{children:React.ReactNode},{hasError:boolean}>{\n  state={hasError:false};\n  static getDerivedStateFromError(){return {hasError:true}}\n  componentDidCatch(error:unknown){console.error("Calisthenics Coach render error",error)}\n  render(){\n    if(this.state.hasError){\n      return <div className="min-h-[100dvh] bg-ink text-white grid place-items-center p-6">\n        <div className="w-full max-w-md rounded-3xl border border-line bg-panel p-6 text-center shadow-xl">\n          <div className="eyebrow">CALISTHENICS COACH</div>\n          <h1 className="mt-3 text-3xl">Something went wrong.</h1>\n          <p className="mt-3 text-sm leading-6 text-muted">The current screen failed to render. Your saved workout data is kept locally.</p>\n          <button className="primary-cta mt-6 w-full" onClick={()=>location.reload()}>RELOAD APP</button>\n        </div>\n      </div>;\n    }\n    return this.props.children;\n  }\n}\n'''
if 'function registerServiceWorker()' not in t: t=t.replace(marker,marker+extra)
t=t.replace('createRoot(document.getElementById("root")!).render(<App/>);','registerServiceWorker();\ncreateRoot(document.getElementById("root")!).render(<AppErrorBoundary><App/></AppErrorBoundary>);')
main.write_text(t)

h=html.read_text()
if 'manifest.webmanifest' not in h:
    h=h.replace('<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>','<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>\n<link rel="manifest" href="/manifest.webmanifest"/>\n<link rel="icon" href="/favicon.svg" type="image/svg+xml"/>')
html.write_text(h)

c=css.read_text()
polish='''\n/* PHASE 5 — production polish */\nhtml{scroll-behavior:smooth;overscroll-behavior-y:none}\nbody{min-height:100dvh;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}\nbutton,a,input,select,textarea{touch-action:manipulation}\nbutton:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid rgba(183,156,255,.8);outline-offset:2px}\n::selection{background:rgba(139,92,246,.32);color:#fff}\n.safe-bottom{padding-bottom:max(env(safe-area-inset-bottom),.5rem)}\n.safe-top{padding-top:max(env(safe-area-inset-top),.5rem)}\n.interactive{transition:transform .18s cubic-bezier(.22,1,.36,1),border-color .18s ease,background-color .18s ease,box-shadow .18s ease}\n.interactive:hover{border-color:rgba(183,156,255,.28);box-shadow:0 10px 30px rgba(0,0,0,.16)}\n.interactive:active{transform:scale(.985)}\n.enter{animation:cc-enter .32s cubic-bezier(.22,1,.36,1) both}\n.stagger>*{animation:cc-enter .35s cubic-bezier(.22,1,.36,1) both}\n.stagger>*:nth-child(2){animation-delay:.035s}.stagger>*:nth-child(3){animation-delay:.07s}.stagger>*:nth-child(4){animation-delay:.105s}.stagger>*:nth-child(5){animation-delay:.14s}.stagger>*:nth-child(6){animation-delay:.175s}\n@keyframes cc-enter{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}\n.skeleton{position:relative;overflow:hidden;background:#151519;border-radius:12px}\n.skeleton::after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.045),transparent);animation:cc-shimmer 1.5s infinite}\n@keyframes cc-shimmer{100%{transform:translateX(100%)}}\n.empty-state{border:1px dashed #2c2c34;background:rgba(17,17,20,.55);border-radius:22px;padding:1.4rem;text-align:center}\n.status-dot{width:7px;height:7px;border-radius:50%;display:inline-block;flex:0 0 auto}\n.status-dot.good{background:#67d39a;box-shadow:0 0 14px rgba(103,211,154,.35)}\n.status-dot.warn{background:#d6ab63;box-shadow:0 0 14px rgba(214,171,99,.25)}\n.status-dot.bad{background:#ee7777;box-shadow:0 0 14px rgba(238,119,119,.25)}\n.metric-value{font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1}\n@media(max-width:520px){h1{font-size:clamp(34px,11vw,50px)}.hero-mission{border-radius:22px}.workout-row{padding-block:.9rem}.counter-input{font-size:28px}}\n@media(min-width:900px){main{padding-left:1rem;padding-right:1rem}.glass-panel,.weekly-review,.hero-mission{box-shadow:0 16px 48px rgba(0,0,0,.14)}}\n@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.enter,.stagger>*{animation:none}.skeleton::after{animation:none}button{transition:none!important}.interactive:hover{box-shadow:none}}\n'''
if 'PHASE 5 — production polish' not in c:c+=polish
css.write_text(c)

(root/'manifest.webmanifest').write_text('''{\n  "name":"Calisthenics Coach",\n  "short_name":"Coach",\n  "description":"Premium calisthenics training and progression tracker.",\n  "start_url":"/",\n  "display":"standalone",\n  "background_color":"#09090B",\n  "theme_color":"#09090B",\n  "orientation":"portrait-primary",\n  "icons":[{"src":"/favicon.svg","sizes":"any","type":"image/svg+xml","purpose":"any maskable"}]\n}\n''')
(root/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#09090B"/><path d="M18 43V21M46 43V21M18 32h28" stroke="#B79CFF" stroke-width="6" stroke-linecap="round"/></svg>')
(root/'sw.js').write_text('''const CACHE="cc-shell-v5";\nconst SHELL=["/","/manifest.webmanifest","/favicon.svg"];\nself.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));\nself.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));\nself.addEventListener("fetch",e=>{const r=e.request;if(r.method!=="GET")return;e.respondWith(fetch(r).then(res=>{if(new URL(r.url).origin===self.location.origin){const copy=res.clone();caches.open(CACHE).then(c=>c.put(r,copy)).catch(()=>{})}return res}).catch(()=>caches.match(r).then(x=>x||caches.match("/"))))});\n''')
(root/'PHASE5_POLISH.md').write_text('''# Phase 5 — Polish\n\nImplemented production polish without adding new product scope:\n- PWA manifest + favicon + service worker shell fallback\n- render error boundary with local-data reassurance\n- focus-visible accessibility\n- prefers-reduced-motion support\n- touch/overscroll/safe-area handling\n- consistent micro-interactions and entry motion\n- skeleton/empty-state primitives\n- typography/readability refinements\n- mobile and desktop polish\n\nExisting haptics, sound, wake lock and timer feedback remain in the workout player.\n''')
