-- V14.4 — canonical exercise catalog + progression graph

create table if not exists public.exercise_catalog (
  id text primary key, name text not null, category text not null, skill text not null, pattern text not null,
  kind text not null, difficulty smallint not null check (difficulty between 1 and 5),
  equipment text[] not null default '{}', side_mode text not null default 'bilateral',
  rep_min integer, rep_max integer, hold_min integer, hold_max integer, rest_sec integer,
  default_target text, detail text, cue text, active boolean not null default true, sort_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.exercise_progressions (
  from_exercise_id text not null references public.exercise_catalog(id) on delete cascade,
  to_exercise_id text not null references public.exercise_catalog(id) on delete cascade,
  relation_type text not null default 'progression',
  promotion_rule jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0, primary key (from_exercise_id,to_exercise_id), check (from_exercise_id <> to_exercise_id)
);

alter table public.exercise_catalog enable row level security;
alter table public.exercise_progressions enable row level security;
drop policy if exists "active exercise catalog readable" on public.exercise_catalog;
create policy "active exercise catalog readable" on public.exercise_catalog for select to authenticated using (active = true);
drop policy if exists "active exercise progressions readable" on public.exercise_progressions;
create policy "active exercise progressions readable" on public.exercise_progressions for select to authenticated using (exists (select 1 from public.exercise_catalog e where e.id=from_exercise_id and e.active));
revoke all on public.exercise_catalog from anon, public; grant select on public.exercise_catalog to authenticated;
revoke all on public.exercise_progressions from anon, public; grant select on public.exercise_progressions to authenticated;

insert into public.exercise_catalog (id,name,category,skill,pattern,kind,difficulty,equipment,side_mode,rep_min,rep_max,hold_min,hold_max,rest_sec,default_target,detail,cue,sort_order) values
('active-hang','Active Hang','PREHAB','OAP','vertical_pull','HOLD',1,array['bar'],'bilateral',null,null,15,20,45,'15–20 sec','15–20 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('scap-pullup','Scapular Pull-up','PREHAB','OAP','vertical_pull','REPS',1,array['bar'],'bilateral',8,12,null,null,60,'8–12','8–12 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-face-pull','Band Face Pull','PREHAB','SHOULDER','horizontal_pull','REPS',1,array['band'],'bilateral',15,25,null,null,60,'15–25','15–25 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-straight-arm-pulldown','Band Straight-Arm Pulldown','PREHAB','FRONT_LEVER','straight_arm_pull','REPS',1,array['band'],'bilateral',12,20,null,null,60,'12–20','12–20 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-external-rotation','Band External Rotation','PREHAB','SHOULDER','rotation','REPS',1,array['band'],'bilateral',15,25,null,null,45,'15–25','15–25 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-curl-prep','Light Band Curl + Elbow Prep','PREHAB','OAP','elbow_flexion','REPS',1,array['band'],'bilateral',15,25,null,null,45,'15–25','15–25 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('wrist-rocks','Wrist Rocks','PREHAB','PLANCHE','wrist','REPS',1,array['floor'],'bilateral',8,15,null,null,30,'8–15','8–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('scap-pushup','Scapular Push-up','PREHAB','PLANCHE','horizontal_push','REPS',1,array['floor'],'bilateral',10,15,null,null,45,'10–15','10–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('german-hang','German Hang','PREHAB','BACK_LEVER','straight_arm_pull','HOLD',2,array['bar'],'bilateral',null,null,15,30,60,'15–30 sec','15–30 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pushup','Push-up','PUSH','GENERAL','horizontal_push','REPS',1,array['floor'],'bilateral',10,25,null,null,90,'10–25','10–25 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('close-pushup','Close-Grip Push-up','PUSH','GENERAL','horizontal_push','REPS',2,array['floor'],'bilateral',8,20,null,null,120,'8–20','8–20 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('diamond-pushup','Diamond Push-up','PUSH','GENERAL','horizontal_push','REPS',2,array['floor'],'bilateral',8,15,null,null,120,'8–15','8–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pseudo-planche-pushup','Pseudo Planche Push-up','PUSH','PLANCHE','straight_arm_push','REPS',3,array['floor'],'bilateral',5,12,null,null,150,'5–12','5–12 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('planche-lean','Planche Lean','SKILL','PLANCHE','straight_arm_push','HOLD',2,array['parallettes','floor'],'bilateral',null,null,10,25,90,'10–25 sec','10–25 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('tuck-planche','Tuck Planche','SKILL','PLANCHE','straight_arm_push','HOLD',3,array['parallettes'],'bilateral',null,null,5,12,150,'5–12 sec','5–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('advanced-tuck-planche','Advanced Tuck Planche','SKILL','PLANCHE','straight_arm_push','HOLD',4,array['parallettes'],'bilateral',null,null,5,10,180,'5–10 sec','5–10 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('straddle-planche','Straddle Planche','SKILL','PLANCHE','straight_arm_push','HOLD',5,array['parallettes'],'bilateral',null,null,3,8,210,'3–8 sec','3–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('full-planche','Full Planche','SKILL','PLANCHE','straight_arm_push','HOLD',5,array['parallettes'],'bilateral',null,null,2,6,240,'2–6 sec','2–6 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('planche-negative','Planche Negative','SKILL','PLANCHE','straight_arm_push','REPS',5,array['parallettes'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-planche','Band-Assisted Planche','SKILL','PLANCHE','straight_arm_push','HOLD',4,array['parallettes','band'],'bilateral',null,null,5,12,150,'5–12 sec','5–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pike-pushup','Pike Push-up','PUSH','HSPU','vertical_push','REPS',2,array['floor'],'bilateral',6,15,null,null,150,'6–15','6–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('feet-elevated-pike','Feet-Elevated Pike Push-up','PUSH','HSPU','vertical_push','REPS',3,array['bench','floor'],'bilateral',5,12,null,null,150,'5–12','5–12 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('wall-handstand','Wall Handstand','SKILL','HANDSTAND','vertical_push','HOLD',2,array['wall'],'bilateral',null,null,20,45,90,'20–45 sec','20–45 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('wall-hspu','Wall HSPU','SKILL','HSPU','vertical_push','REPS',4,array['wall'],'bilateral',3,8,null,null,180,'3–8','3–8 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('deficit-wall-hspu','Deficit Wall HSPU','SKILL','HSPU','vertical_push','REPS',5,array['parallettes','wall'],'bilateral',2,6,null,null,210,'2–6','2–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('freestanding-hspu','Freestanding HSPU','SKILL','HSPU','vertical_push','REPS',5,array['floor'],'bilateral',1,5,null,null,210,'1–5','1–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-lateral-raise','Band Lateral Raise','ACCESSORY','SHOULDER','abduction','REPS',2,array['band'],'bilateral',15,25,null,null,75,'15–25','15–25 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-triceps-pressdown','Band Triceps Pressdown','ACCESSORY','TRICEPS','elbow_extension','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-overhead-triceps','Band Overhead Triceps Extension','ACCESSORY','TRICEPS','elbow_extension','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pullup','Pull-up','PULL','GENERAL','vertical_pull','REPS',2,array['bar'],'bilateral',5,15,null,null,150,'5–15','5–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('chinup','Chin-up','PULL','GENERAL','vertical_pull','REPS',2,array['bar'],'bilateral',5,15,null,null,150,'5–15','5–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('close-grip-chin','Close-Grip Chin-up','PULL','GENERAL','vertical_pull','REPS',2,array['bar'],'bilateral',5,12,null,null,150,'5–12','5–12 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('wide-pullup','Wide Pull-up','PULL','GENERAL','vertical_pull','REPS',3,array['bar'],'bilateral',5,10,null,null,165,'5–10','5–10 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('chest-to-bar','Chest-to-Bar Pull-up','PULL','MUSCLE_UP','vertical_pull','REPS',3,array['bar'],'bilateral',4,8,null,null,180,'4–8','4–8 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('high-pullup','High Pull-up','PULL','MUSCLE_UP','vertical_pull','REPS',4,array['bar'],'bilateral',3,5,null,null,180,'3–5','3–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('explosive-pullup','Explosive Pull-up','PULL','MUSCLE_UP','vertical_pull','REPS',4,array['bar'],'bilateral',3,6,null,null,180,'3–6','3–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('archer-pullup','Archer Pull-up','PULL','OAP','unilateral_pull','REPS',4,array['bar'],'left_right',4,8,null,null,165,'4–8 / side','4–8 / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('typewriter-pullup','Typewriter Pull-up','PULL','OAP','unilateral_pull','REPS',4,array['bar'],'left_right',3,6,null,null,180,'3–6 / side','3–6 / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('assisted-oap','Assisted One Arm Pull-up','SKILL','OAP','unilateral_pull','REPS',3,array['bar','band'],'left_right',2,5,null,null,180,'2–5 / arm','2–5 / arm • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('oap-negative','One Arm Pull-up Negative','SKILL','OAP','unilateral_pull','REPS',4,array['bar'],'left_right',2,4,null,null,210,'2–4 / arm','2–4 / arm • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('oap-isometric','One Arm Pull-up Isometric','SKILL','OAP','unilateral_pull','HOLD',4,array['bar'],'left_right',null,null,3,8,210,'3–8 sec / arm','3–8 sec / arm • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-arm-chin','One Arm Chin-up','SKILL','OAP','unilateral_pull','REPS',5,array['bar'],'left_right',1,4,null,null,240,'1–4 / arm','1–4 / arm • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-arm-pullup','One Arm Pull-up','SKILL','OAP','unilateral_pull','REPS',5,array['bar'],'left_right',1,3,null,null,240,'1–3 / arm','1–3 / arm • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-curl','Band Curl','ACCESSORY','ELBOW','elbow_flexion','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('tuck-front-lever','Tuck Front Lever','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',2,array['bar'],'bilateral',null,null,5,15,120,'5–15 sec','5–15 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('advanced-tuck-front-lever','Advanced Tuck Front Lever','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',3,array['bar'],'bilateral',null,null,5,12,150,'5–12 sec','5–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-leg-front-lever','One-Leg Front Lever','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',4,array['bar'],'bilateral',null,null,4,10,180,'4–10 sec','4–10 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('straddle-front-lever','Straddle Front Lever','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',5,array['bar'],'bilateral',null,null,3,8,210,'3–8 sec','3–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('full-front-lever','Full Front Lever','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',5,array['bar'],'bilateral',null,null,3,8,210,'3–8 sec','3–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('front-lever-touch','Front Touch','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',5,array['bar'],'bilateral',null,null,8,12,210,'8–12 sec','8–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('assisted-front-touch','Assisted Front Touch','SKILL','FRONT_LEVER','straight_arm_pull','HOLD',4,array['bar','band'],'bilateral',null,null,5,8,120,'5–8 sec','5–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('tuck-fl-row','Tuck Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',2,array['bar'],'bilateral',5,10,null,null,120,'5–10','5–10 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('advanced-tuck-fl-row','Advanced Tuck Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',3,array['bar'],'bilateral',4,8,null,null,150,'4–8','4–8 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-leg-fl-row','One-Leg Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',4,array['bar'],'bilateral',3,6,null,null,180,'3–6','3–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('straddle-fl-row','Straddle Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',5,array['bar'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('full-fl-row','Full Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',5,array['bar'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('full-fl-pullup','Full Front Lever Pull-up','SKILL','FRONT_LEVER','straight_arm_pull','REPS',5,array['bar'],'bilateral',1,4,null,null,210,'1–4','1–4 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-fl-pullup','Band-Assisted FL Pull-up','SKILL','FRONT_LEVER','straight_arm_pull','REPS',4,array['bar','band'],'bilateral',3,6,null,null,180,'3–6','3–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('fl-raise','Front Lever Raise','SKILL','FRONT_LEVER','straight_arm_pull','REPS',5,array['bar'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-straight-arm-pulldown-fl','Band Straight-Arm Pulldown','ACCESSORY','FRONT_LEVER','straight_arm_pull','REPS',2,array['band'],'bilateral',12,20,null,null,75,'12–20','12–20 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('band-muscle-up','Band-Assisted Muscle-up','SKILL','MUSCLE_UP','transition','REPS',3,array['bar','band'],'bilateral',2,5,null,null,180,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('jumping-muscle-up','Jumping Muscle-up','SKILL','MUSCLE_UP','transition','REPS',2,array['bar'],'bilateral',3,6,null,null,150,'3–6','3–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('low-bar-transition','Low-Bar Muscle-up Transition','SKILL','MUSCLE_UP','transition','REPS',2,array['low_bar'],'bilateral',5,10,null,null,120,'5–10','5–10 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('muscle-up-negative','Muscle-up Negative','SKILL','MUSCLE_UP','transition','REPS',3,array['bar'],'bilateral',2,5,null,null,180,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('strict-muscle-up','Strict Muscle-up','SKILL','MUSCLE_UP','transition','REPS',5,array['bar'],'bilateral',1,5,null,null,210,'1–5','1–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('weighted-muscle-up','Weighted Muscle-up','SKILL','MUSCLE_UP','transition','REPS',5,array['bar','weight'],'bilateral',1,5,null,null,240,'1–5','1–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('skin-the-cat','Skin the Cat','SKILL','BACK_LEVER','straight_arm_pull','REPS',2,array['bar'],'bilateral',3,8,null,null,120,'3–8','3–8 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('tuck-back-lever','Tuck Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',3,array['bar'],'bilateral',null,null,5,12,150,'5–12 sec','5–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('advanced-tuck-back-lever','Advanced Tuck Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',4,array['bar'],'bilateral',null,null,4,10,180,'4–10 sec','4–10 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-leg-back-lever','One-Leg Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',4,array['bar'],'bilateral',null,null,4,8,180,'4–8 sec','4–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('straddle-back-lever','Straddle Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',5,array['bar'],'bilateral',null,null,3,8,210,'3–8 sec','3–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('full-back-lever','Full Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',5,array['bar'],'bilateral',null,null,3,8,210,'3–8 sec','3–8 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('side-plank','Side Plank','CORE','HUMAN_FLAG','anti_lateral_flexion','HOLD',1,array['floor'],'left_right',null,null,20,45,60,'20–45 sec / side','20–45 sec / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('tuck-human-flag','Tuck Human Flag','SKILL','HUMAN_FLAG','lateral_push_pull','HOLD',3,array['bar'],'left_right',null,null,3,10,150,'3–10 sec / side','3–10 sec / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('one-leg-human-flag','One-Leg Human Flag','SKILL','HUMAN_FLAG','lateral_push_pull','HOLD',4,array['bar'],'left_right',null,null,3,8,180,'3–8 sec / side','3–8 sec / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('straddle-human-flag','Straddle Human Flag','SKILL','HUMAN_FLAG','lateral_push_pull','HOLD',5,array['bar'],'left_right',null,null,2,6,210,'2–6 sec / side','2–6 sec / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('human-flag','Human Flag','SKILL','HUMAN_FLAG','lateral_push_pull','HOLD',5,array['bar'],'left_right',null,null,2,6,210,'2–6 sec / side','2–6 sec / side • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('hollow-body-hold','Hollow Body Hold','CORE','CORE','anti_extension','HOLD',1,array['floor'],'bilateral',null,null,20,40,75,'20–40 sec','20–40 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('hollow-rock','Hollow Body Rock','CORE','CORE','anti_extension','REPS',2,array['floor'],'bilateral',10,20,null,null,60,'10–20','10–20 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('reverse-crunch','Reverse Crunch / Hip Lift','CORE','CORE','hip_flexion','REPS',1,array['floor'],'bilateral',12,20,null,null,75,'12–20','12–20 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('hanging-knee-raise','Hanging Knee Raise','CORE','CORE','hip_flexion','REPS',2,array['bar'],'bilateral',10,15,null,null,75,'10–15','10–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('hanging-leg-raise','Hanging Leg Raise','CORE','CORE','hip_flexion','REPS',3,array['bar'],'bilateral',8,15,null,null,90,'8–15','8–15 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('toes-to-bar','Strict Toes-to-Bar','CORE','CORE','hip_flexion','REPS',4,array['bar'],'bilateral',5,12,null,null,120,'5–12','5–12 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('dragon-flag-negative','Dragon Flag Negative','CORE','CORE','anti_extension','REPS',3,array['bench'],'bilateral',3,8,null,null,120,'3–8','3–8 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('dragon-flag','Dragon Flag','CORE','CORE','anti_extension','REPS',4,array['bench'],'bilateral',2,6,null,null,150,'2–6','2–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('l-sit','L-Sit','CORE','L_SIT','compression','HOLD',3,array['parallettes'],'bilateral',null,null,8,20,120,'8–20 sec','8–20 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('v-sit','V-Sit','CORE','V_SIT','compression','HOLD',5,array['parallettes'],'bilateral',null,null,3,12,150,'3–12 sec','3–12 sec • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('windshield-wiper','Hanging Windshield Wiper','CORE','CORE','anti_rotation','REPS',4,array['bar'],'bilateral',4,10,null,null,120,'4–10','4–10 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('bodyweight-squat','Bodyweight Squat','LEGS','GENERAL','knee_dominant','REPS',1,array['floor'],'bilateral',10,30,null,null,75,'10–30','10–30 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('bulgarian-split-squat','Bulgarian Split Squat','LEGS','GENERAL','unilateral_knee','REPS',3,array['bench'],'left_right',6,10,null,null,150,'6–10 / leg','6–10 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('assisted-pistol','Assisted Pistol Squat','LEGS','PISTOL','unilateral_knee','REPS',3,array['bar'],'left_right',5,10,null,null,120,'5–10 / leg','5–10 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pistol-squat','Strict Pistol Squat','LEGS','PISTOL','unilateral_knee','REPS',4,array['floor'],'left_right',4,10,null,null,150,'4–10 / leg','4–10 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('deficit-pistol','Deficit Pistol Squat','LEGS','PISTOL','unilateral_knee','REPS',5,array['platform'],'left_right',3,8,null,null,180,'3–8 / leg','3–8 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('single-leg-rdl','Single-Leg RDL','LEGS','GENERAL','hip_hinge','REPS',2,array['floor'],'left_right',8,12,null,null,100,'8–12 / leg','8–12 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('nordic-negative','Nordic Curl Negative','LEGS','HAMSTRING','knee_flexion','REPS',4,array['floor'],'bilateral',3,6,null,null,150,'3–6','3–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('nordic-curl','Nordic Curl','LEGS','HAMSTRING','knee_flexion','REPS',5,array['floor'],'bilateral',2,6,null,null,180,'2–6','2–6 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('single-leg-calf','Single-Leg Calf Raise','LEGS','CALF','plantarflexion','REPS',2,array['floor'],'left_right',12,20,null,null,75,'12–20 / leg','12–20 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('broad-jump','Broad Jump','LEGS','ATHLETIC','horizontal_power','REPS',3,array['floor'],'bilateral',2,5,null,null,150,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('countermovement-jump','Countermovement Jump','LEGS','ATHLETIC','vertical_power','REPS',3,array['floor'],'bilateral',2,5,null,null,150,'2–5','2–5 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('split-jump','Split Jump / Jump Lunge','LEGS','ATHLETIC','unilateral_power','REPS',3,array['floor'],'left_right',5,8,null,null,120,'5–8 / leg','5–8 / leg • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100),
('pogo-hops','Pogo Hops','LEGS','ATHLETIC','ankle_power','REPS',2,array['floor'],'bilateral',15,30,null,null,60,'15–30','15–30 • controlled quality • stop before technique breaks.','Clean reps, stable positions, no forced pain.',100)
on conflict (id) do update set name=excluded.name,category=excluded.category,skill=excluded.skill,pattern=excluded.pattern,kind=excluded.kind,difficulty=excluded.difficulty,equipment=excluded.equipment,side_mode=excluded.side_mode,rep_min=excluded.rep_min,rep_max=excluded.rep_max,hold_min=excluded.hold_min,hold_max=excluded.hold_max,rest_sec=excluded.rest_sec,default_target=excluded.default_target,detail=excluded.detail,cue=excluded.cue,sort_order=excluded.sort_order,updated_at=now();

insert into public.exercise_progressions (from_exercise_id,to_exercise_id,relation_type,sort_order) values
('planche-lean','tuck-planche','progression',0),
('tuck-planche','advanced-tuck-planche','progression',1),
('advanced-tuck-planche','straddle-planche','progression',2),
('straddle-planche','full-planche','progression',3),
('band-planche','tuck-planche','progression',4),
('pike-pushup','feet-elevated-pike','progression',5),
('feet-elevated-pike','wall-hspu','progression',6),
('wall-hspu','deficit-wall-hspu','progression',7),
('deficit-wall-hspu','freestanding-hspu','progression',8),
('pullup','chest-to-bar','progression',9),
('chest-to-bar','high-pullup','progression',10),
('high-pullup','explosive-pullup','progression',11),
('explosive-pullup','band-muscle-up','prerequisite',12),
('band-muscle-up','strict-muscle-up','progression',13),
('strict-muscle-up','weighted-muscle-up','progression',14),
('pullup','archer-pullup','progression',15),
('archer-pullup','typewriter-pullup','progression',16),
('typewriter-pullup','assisted-oap','progression',17),
('assisted-oap','oap-negative','progression',18),
('oap-negative','oap-isometric','progression',19),
('oap-isometric','one-arm-chin','progression',20),
('one-arm-chin','one-arm-pullup','progression',21),
('tuck-front-lever','advanced-tuck-front-lever','progression',22),
('advanced-tuck-front-lever','one-leg-front-lever','progression',23),
('one-leg-front-lever','straddle-front-lever','progression',24),
('straddle-front-lever','full-front-lever','progression',25),
('full-front-lever','front-lever-touch','skill_variant',26),
('assisted-front-touch','front-lever-touch','progression',27),
('tuck-fl-row','advanced-tuck-fl-row','progression',28),
('advanced-tuck-fl-row','one-leg-fl-row','progression',29),
('one-leg-fl-row','straddle-fl-row','progression',30),
('straddle-fl-row','full-fl-row','progression',31),
('full-fl-row','full-fl-pullup','progression',32),
('band-fl-pullup','full-fl-pullup','progression',33),
('skin-the-cat','tuck-back-lever','progression',34),
('tuck-back-lever','advanced-tuck-back-lever','progression',35),
('advanced-tuck-back-lever','one-leg-back-lever','progression',36),
('one-leg-back-lever','straddle-back-lever','progression',37),
('straddle-back-lever','full-back-lever','progression',38),
('side-plank','tuck-human-flag','prerequisite',39),
('tuck-human-flag','one-leg-human-flag','progression',40),
('one-leg-human-flag','straddle-human-flag','progression',41),
('straddle-human-flag','human-flag','progression',42),
('hanging-knee-raise','hanging-leg-raise','progression',43),
('hanging-leg-raise','toes-to-bar','progression',44),
('dragon-flag-negative','dragon-flag','progression',45),
('l-sit','v-sit','progression',46),
('assisted-pistol','pistol-squat','progression',47),
('pistol-squat','deficit-pistol','progression',48),
('nordic-negative','nordic-curl','progression',49) on conflict (from_exercise_id,to_exercise_id) do update set relation_type=excluded.relation_type,sort_order=excluded.sort_order;

create index if not exists exercise_catalog_skill_idx on public.exercise_catalog(skill,active,difficulty);
create index if not exists exercise_catalog_category_idx on public.exercise_catalog(category,active);
create index if not exists exercise_progressions_from_idx on public.exercise_progressions(from_exercise_id,sort_order);
create index if not exists exercise_progressions_to_idx on public.exercise_progressions(to_exercise_id);

comment on table public.exercise_catalog is 'Canonical coach-approved exercise library. Program blocks reference these stable IDs.';
comment on table public.exercise_progressions is 'Directed progression graph used by Edit Plan and progression decisions.';
