-- V14.4 — complete the catalog rows not present in the first seed.
-- Idempotent: safe to run after 005.

insert into public.exercise_catalog(id,name,category,skill,pattern,kind,difficulty,equipment,side_mode,rep_min,rep_max,hold_min,hold_max,rest_sec,default_target,detail) values
('active-hang','Active Hang','PREHAB','OAP','vertical_pull','HOLD',1,array['bar'],'bilateral',null,null,15,20,45,'15–20 sec','15–20 sec • controlled quality • stop before technique breaks.'),
('scap-pullup','Scapular Pull-up','PREHAB','OAP','vertical_pull','REPS',1,array['bar'],'bilateral',8,12,null,null,60,'8–12','8–12 • controlled quality • stop before technique breaks.'),
('band-face-pull','Band Face Pull','PREHAB','SHOULDER','horizontal_pull','REPS',1,array['band'],'bilateral',15,25,null,null,60,'15–25','15–25 • controlled quality • stop before technique breaks.'),
('band-straight-arm-pulldown','Band Straight-Arm Pulldown','PREHAB','FRONT_LEVER','straight_arm_pull','REPS',1,array['band'],'bilateral',12,20,null,null,60,'12–20','12–20 • controlled quality • stop before technique breaks.'),
('band-external-rotation','Band External Rotation','PREHAB','SHOULDER','rotation','REPS',1,array['band'],'bilateral',15,25,null,null,45,'15–25','15–25 • controlled quality • stop before technique breaks.'),
('band-curl-prep','Light Band Curl + Elbow Prep','PREHAB','OAP','elbow_flexion','REPS',1,array['band'],'bilateral',15,25,null,null,45,'15–25','15–25 • controlled quality • stop before technique breaks.'),
('wrist-rocks','Wrist Rocks','PREHAB','PLANCHE','wrist','REPS',1,array['floor'],'bilateral',8,15,null,null,30,'8–15','8–15 • controlled quality • stop before technique breaks.'),
('scap-pushup','Scapular Push-up','PREHAB','PLANCHE','horizontal_push','REPS',1,array['floor'],'bilateral',10,15,null,null,45,'10–15','10–15 • controlled quality • stop before technique breaks.'),
('german-hang','German Hang','PREHAB','BACK_LEVER','straight_arm_pull','HOLD',2,array['bar'],'bilateral',null,null,15,30,60,'15–30 sec','15–30 sec • controlled quality • stop before technique breaks.'),
('close-pushup','Close-Grip Push-up','PUSH','GENERAL','horizontal_push','REPS',2,array['floor'],'bilateral',8,20,null,null,120,'8–20','8–20 • controlled quality • stop before technique breaks.'),
('planche-negative','Planche Negative','SKILL','PLANCHE','straight_arm_push','REPS',5,array['parallettes'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.'),
('band-planche','Band-Assisted Planche','SKILL','PLANCHE','straight_arm_push','HOLD',4,array['parallettes','band'],'bilateral',null,null,5,12,150,'5–12 sec','5–12 sec • controlled quality • stop before technique breaks.'),
('wall-handstand','Wall Handstand','SKILL','HANDSTAND','vertical_push','HOLD',2,array['wall'],'bilateral',null,null,20,45,90,'20–45 sec','20–45 sec • controlled quality • stop before technique breaks.'),
('deficit-wall-hspu','Deficit Wall HSPU','SKILL','HSPU','vertical_push','REPS',5,array['parallettes','wall'],'bilateral',2,6,null,null,210,'2–6','2–6 • controlled quality • stop before technique breaks.'),
('band-lateral-raise','Band Lateral Raise','ACCESSORY','SHOULDER','abduction','REPS',2,array['band'],'bilateral',15,25,null,null,75,'15–25','15–25 • controlled quality • stop before technique breaks.'),
('band-triceps-pressdown','Band Triceps Pressdown','ACCESSORY','TRICEPS','elbow_extension','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.'),
('band-overhead-triceps','Band Overhead Triceps Extension','ACCESSORY','TRICEPS','elbow_extension','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.'),
('wide-pullup','Wide Pull-up','PULL','GENERAL','vertical_pull','REPS',3,array['bar'],'bilateral',5,10,null,null,165,'5–10','5–10 • controlled quality • stop before technique breaks.'),
('band-curl','Band Curl','ACCESSORY','ELBOW','elbow_flexion','REPS',2,array['band'],'bilateral',15,30,null,null,75,'15–30','15–30 • controlled quality • stop before technique breaks.'),
('straddle-fl-row','Straddle Front Lever Row','SKILL','FRONT_LEVER','horizontal_pull','REPS',5,array['bar'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.'),
('fl-raise','Front Lever Raise','SKILL','FRONT_LEVER','straight_arm_pull','REPS',5,array['bar'],'bilateral',2,5,null,null,210,'2–5','2–5 • controlled quality • stop before technique breaks.'),
('band-straight-arm-pulldown-fl','Band Straight-Arm Pulldown','ACCESSORY','FRONT_LEVER','straight_arm_pull','REPS',2,array['band'],'bilateral',12,20,null,null,75,'12–20','12–20 • controlled quality • stop before technique breaks.'),
('low-bar-transition','Low-Bar Muscle-up Transition','SKILL','MUSCLE_UP','transition','REPS',2,array['low_bar'],'bilateral',5,10,null,null,120,'5–10','5–10 • controlled quality • stop before technique breaks.'),
('weighted-muscle-up','Weighted Muscle-up','SKILL','MUSCLE_UP','transition','REPS',5,array['bar','weight'],'bilateral',1,5,null,null,240,'1–5','1–5 • controlled quality • stop before technique breaks.'),
('one-leg-back-lever','One-Leg Back Lever','SKILL','BACK_LEVER','straight_arm_pull','HOLD',4,array['bar'],'bilateral',null,null,4,8,180,'4–8 sec','4–8 sec • controlled quality • stop before technique breaks.'),
('hollow-rock','Hollow Body Rock','CORE','CORE','anti_extension','REPS',2,array['floor'],'bilateral',10,20,null,null,60,'10–20','10–20 • controlled quality • stop before technique breaks.'),
('reverse-crunch','Reverse Crunch / Hip Lift','CORE','CORE','hip_flexion','REPS',1,array['floor'],'bilateral',12,20,null,null,75,'12–20','12–20 • controlled quality • stop before technique breaks.'),
('toes-to-bar','Strict Toes-to-Bar','CORE','CORE','hip_flexion','REPS',4,array['bar'],'bilateral',5,12,null,null,120,'5–12','5–12 • controlled quality • stop before technique breaks.'),
('windshield-wiper','Hanging Windshield Wiper','CORE','CORE','anti_rotation','REPS',4,array['bar'],'bilateral',4,10,null,null,120,'4–10','4–10 • controlled quality • stop before technique breaks.'),
('bodyweight-squat','Bodyweight Squat','LEGS','GENERAL','knee_dominant','REPS',1,array['floor'],'bilateral',10,30,null,null,75,'10–30','10–30 • controlled quality • stop before technique breaks.'),
('deficit-pistol','Deficit Pistol Squat','LEGS','PISTOL','unilateral_knee','REPS',5,array['platform'],'left_right',3,8,null,null,180,'3–8 / leg','3–8 / leg • controlled quality • stop before technique breaks.'),
('single-leg-rdl','Single-Leg RDL','LEGS','GENERAL','hip_hinge','REPS',2,array['floor'],'left_right',8,12,null,null,100,'8–12 / leg','8–12 / leg • controlled quality • stop before technique breaks.'),
('single-leg-calf','Single-Leg Calf Raise','LEGS','CALF','plantarflexion','REPS',2,array['floor'],'left_right',12,20,null,null,75,'12–20 / leg','12–20 / leg • controlled quality • stop before technique breaks.'),
('split-jump','Split Jump / Jump Lunge','LEGS','ATHLETIC','unilateral_power','REPS',3,array['floor'],'left_right',5,8,null,null,120,'5–8 / leg','5–8 / leg • controlled quality • stop before technique breaks.'),
('pogo-hops','Pogo Hops','LEGS','ATHLETIC','ankle_power','REPS',2,array['floor'],'bilateral',15,30,null,null,60,'15–30','15–30 • controlled quality • stop before technique breaks.')
on conflict(id) do update set name=excluded.name,category=excluded.category,skill=excluded.skill,pattern=excluded.pattern,kind=excluded.kind,difficulty=excluded.difficulty,equipment=excluded.equipment,side_mode=excluded.side_mode,rep_min=excluded.rep_min,rep_max=excluded.rep_max,hold_min=excluded.hold_min,hold_max=excluded.hold_max,rest_sec=excluded.rest_sec,default_target=excluded.default_target,detail=excluded.detail,updated_at=now();
